algoritmo "Exercicio_10"
var
  NOME:caractere
  n1,n2,n3,n4,media:real
inicio
  escreval("Cálculo da Média")
  escreval("Digite o nome do aluno:")
  leia(NOME)
  escreval("Digite a nota do primeiro bimestre:")
  leia(n1)
  escreval("Digite a nota do segundo bimestre:")
  leia(n2)
  escreval("Digite a nota do terceiro bimestre:")
  leia(n3)
  escreval("Digite a nota do quarto bimestre:")
  leia(n4)
  media<-(n1+n2+n3+n4)/4
  escreval("A média anual é:",media)
fimalgoritmo
